/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.xavier.csci;

public class Application {
    public String getGreeting() {
        return "Hello from CSCI 260!";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getGreeting());
    }
}
